const db = require('../config/database');

exports.getAllCollections = async (req, res) => {
    try {
        const [rows] = await db.query('SELECT * FROM collections ORDER BY created_at DESC');
        res.json(rows);
    } catch (error) {
        console.error("Error fetching collections:", error);
        res.status(500).json({ message: 'Gagal mengambil data koleksi' });
    }
};

exports.getCollectionById = async (req, res) => {
    try {
        const [rows] = await db.query('SELECT * FROM collections WHERE collection_id = ?', [req.params.id]);
        if (rows.length === 0) {
            return res.status(404).json({ message: 'Koleksi tidak ditemukan' });
        }
        res.json(rows[0]);
    } catch (error) {
        console.error("Error fetching collection:", error);
        res.status(500).json({ message: 'Gagal mengambil data koleksi' });
    }
};

exports.createCollection = async (req, res) => {
    try {
        const { name, slug, description, year } = req.body;
        
        // Handle physical file name
        let cover_image = null;
        if (req.file) {
            cover_image = req.file.filename; // filename generated by multer
        } else {
            return res.status(400).json({ message: 'Cover image wajib diunggah!' });
        }
        
        // Cek nama kembar
        const [existing] = await db.query('SELECT * FROM collections WHERE slug = ?', [slug]);
        if (existing.length > 0) {
            return res.status(400).json({ message: 'Nama/slug koleksi sudah digunakan' });
        }

        const [result] = await db.query(
            'INSERT INTO collections (name, slug, description, year, cover_image) VALUES (?, ?, ?, ?, ?)',
            [name, slug, description, parseInt(year), cover_image]
        );
        
        const [newCollection] = await db.query('SELECT * FROM collections WHERE collection_id = ?', [result.insertId]);
        res.status(201).json({ message: 'Koleksi berhasil ditambahkan', data: newCollection[0] });
    } catch (error) {
        console.error("Error creating collection:", error);
        res.status(500).json({ message: 'Gagal membuat koleksi baru' });
    }
};

exports.updateCollection = async (req, res) => {
    try {
        const { id } = req.params;
        const { name, slug, description, year, cover_image: existingCover } = req.body;
        
        let cover_image = existingCover;
        // If user uploaded a new file, override the existing string
        if (req.file) {
            cover_image = req.file.filename;
        }
        
        // Cek keberadaan data
        const [existing] = await db.query('SELECT * FROM collections WHERE collection_id = ?', [id]);
        if (existing.length === 0) {
            return res.status(404).json({ message: 'Koleksi tidak ditemukan' });
        }

        // Cek kembar
        const [duplicate] = await db.query('SELECT * FROM collections WHERE slug = ? AND collection_id != ?', [slug, id]);
        if (duplicate.length > 0) {
            return res.status(400).json({ message: 'Nama/slug koleksi sudah digunakan oleh data lain' });
        }

        await db.query(
            'UPDATE collections SET name = ?, slug = ?, description = ?, year = ?, cover_image = ? WHERE collection_id = ?',
            [name, slug, description, parseInt(year), cover_image, id]
        );
        
        const [updatedData] = await db.query('SELECT * FROM collections WHERE collection_id = ?', [id]);
        res.json({ message: 'Koleksi berhasil diperbarui', data: updatedData[0] });
    } catch (error) {
        console.error("Error updating collection:", error);
        res.status(500).json({ message: 'Gagal memperbarui koleksi' });
    }
};

exports.deleteCollection = async (req, res) => {
    try {
        const { id } = req.params;
        
        const [existing] = await db.query('SELECT * FROM collections WHERE collection_id = ?', [id]);
        if (existing.length === 0) {
            return res.status(404).json({ message: 'Koleksi tidak ditemukan' });
        }

        await db.query('DELETE FROM collections WHERE collection_id = ?', [id]);
        res.json({ message: 'Koleksi berhasil dihapus' });
    } catch (error) {
        console.error("Error deleting collection:", error);
        res.status(500).json({ message: 'Gagal menghapus koleksi' });
    }
};
